[ build ]
	publish = "_site/"

[[ redirect ]]
	from = "https://wengelxyz.netlify.app/*"
	to = "https://wengel.xyz/:splat"
	status = 200
	force = true

[[ redirect ]]
	from = "/*"
	to = "/404"
	status = 404
